### ISSUE TITLE
fastavro + confluent-kafka avro producer throws TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by FelixKJose** [confluentinc/confluent-kafka-python#979]
Description
===========
I have a simple confluent kafka avro producer as follows:
```
import sys
import uuid
from datetime import datetime

import fastavro as fastavro
from confluent_kafka import avro
from confluent_kafka.avro import AvroProducer


def delivery_callback(err, msg):
    if err:
        sys.stderr.write("%% Message failed delivery: %s\n" % err)
    else:
        sys.stderr.write(
            "%% Message delivered to %s [%d] @ %d\n"
            % (msg.topic(), msg.partition(), msg.offset())
        )


if __name__ == "__main__":
    bootstrap_servers = "127.0.0.1:39092"
    schema_registry_servers = "http://127.0.0.1:48081"

    schema_registry_conf = {"url": schema_registry_servers}

    key_schema_string = """
    {"type": "string"}
    """
    config = {
        "bootstrap.servers": bootstrap_servers,
        "on_delivery": delivery_callback,
        "schema.registry.url": schema_registry_servers,
    }

    key_schema = avro.loads(key_schema_string)
    value_schema = fastavro.schema.load_schema("data/Employee.avsc")
    print(value_schema)

    avro_producer = AvroProducer(
        config=config, default_key_schema=key_schema, default_value_schema=value_schema
    )

    avro_producer.produce(
        topic="employees",
        key=str(uuid.uuid4()),
        value=dict(
            id=1,
            name="Felix",
            role="Eng",
            company="Philips",
            eventDate=datetime.utcnow(),
            address=dict(street="Murrysville", zip=15668),
        ),
    )

    avro_producer.flush()
```
throws following exception:
```
> Traceback (most recent call last):
>   File "/PycharmProjects/ConfluentAvroKafkaProducer/employee_producer.py", line 55, in <module>
>     address=dict(street="Murrysville", zip=15668),
>   File "/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/avro/__init__.py", line 99, in produce
>     value = self._serializer.encode_record_with_schema(topic, value_schema, value)
>   File "/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 108, in encode_record_with_schema
>     schema_id = self.registry_client.register(subject, schema)
>   File "/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 209, in register
>     schema_id = schemas_to_id.get(avro_schema, None)
> TypeError: unhashable type: 'list'
```

**Note: I am attaching the source code with Including pyproject.toml** 
Please find source code:
[ConfluentAvroKafkaProducer.zip](https://github.com/confluentinc/confluent-kafka-python/files/5477937/ConfluentAvroKafkaProducer.zip)

How to reproduce
================
Just try to run employee_producer to publish employee data to employees topic.
Note: you need to have kafka+ schema registry running. 

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
 - [ ] Apache Kafka broker version: **confluentinc/cp-enterprise-kafka:5.1.2**
 - [ ] Client configuration: `{...}`
 - [ ] Operating system: MacOS

 - [ ] Provide client logs (with `'debug': '..'` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by FelixKJose** [comment]
Could someone please help me with this? And guide me if I am doing something wrong.

**Comment by FelixKJose** [comment]
@edenhill Have you ever seen this issue, or am I doing something wrong?

**Comment by FelixKJose** [comment]
Is fastavro supported in confluent kafka? Could someone help me, I am fully blocked with this issue.

**Comment by mhowlett** [comment]
`AvroProducer` is going to be depreciated. Have you tried using `SerializerProducer` as per the example here: https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_producer.py ?

**Comment by FelixKJose** [comment]
@mhowlett I have tried with the SerializerProducer. And I get a different error now:

> [{'type': 'record', 'name': 'Address', 'fields': [{'name': 'street', 'type': 'string'}, {'name': 'zip', 'type': 'int'}], '__fastavro_parsed': True, '__named_schemas': {'Address': {'type': 'record', 'name': 'Address', 'fields': [{'name': 'street', 'type': 'string'}, {'name': 'zip', 'type': 'int'}]}}}, {'type': 'record', 'name': 'Employee', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'name', 'type': 'string'}, {'name': 'role', 'type': 'string'}, {'name': 'company', 'type': 'string'}, {'name': 'eventDate', 'type': {'logicalType': 'timestamp-millis', 'type': 'long'}}, {'name': 'address', 'type': 'Address'}], '__fastavro_parsed': True, '__named_schemas': {'Address': {'type': 'record', 'name': 'Address', 'fields': [{'name': 'street', 'type': 'string'}, {'name': 'zip', 'type': 'int'}]}, 'Employee': {'type': 'record', 'name': 'Employee', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'name', 'type': 'string'}, {'name': 'role', 'type': 'string'}, {'name': 'company', 'type': 'string'}, {'name': 'eventDate', 'type': {'logicalType': 'timestamp-millis', 'type': 'long'}}, {'name': 'address', 'type': 'Address'}]}}}]
> [{'type': 'record', 'name': 'Address', 'fields': [{'name': 'street', 'type': 'string'}, {'name': 'zip', 'type': 'int'}], '__fastavro_parsed': True, '__named_schemas': {'Address': {'type': 'record', 'name': 'Address', 'fields': [{'name': 'street', 'type': 'string'}, {'name': 'zip', 'type': 'int'}]}}}, {'type': 'record', 'name': 'Employee', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'name', 'type': 'string'}, {'name': 'role', 'type': 'string'}, {'name': 'company', 'type': 'string'}, {'name': 'eventDate', 'type': {'logicalType': 'timestamp-millis', 'type': 'long'}}, {'name': 'address', 'type': 'Address'}], '__fastavro_parsed': True, '__named_schemas': {'Address': {'type': 'record', 'name': 'Address', 'fields': [{'name': 'street', 'type': 'string'}, {'name': 'zip', 'type': 'int'}]}, 'Employee': {'type': 'record', 'name': 'Employee', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'name', 'type': 'string'}, {'name': 'role', 'type': 'string'}, {'name': 'company', 'type': 'string'}, {'name': 'eventDate', 'type': {'logicalType': 'timestamp-millis', 'type': 'long'}}, {'name': 'address', 'type': 'Address'}]}}}]
> Traceback (most recent call last):
>   File "/Users/felixkizhakkeljose/PycharmProjects/ConfluentAvroKafkaProducer/employee_producer.py", line 52, in <module>
>     schema_registry_client,
>   File "/Users/felixkizhakkeljose/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/schema_registry/avro.py", line 173, in __init__
>     schema = _schema_loads(schema_str)
>   File "/Users/felixkizhakkeljose/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/schema_registry/avro.py", line 62, in _schema_loads
>     schema_str = schema_str.strip()
> AttributeError: 'list' object has no attribute 'strip'

**Comment by FelixKJose** [comment]
Updated code for the above error:
```
import sys
import uuid
from datetime import datetime

import fastavro as fastavro
from confluent_kafka import avro, SerializingProducer
# Optional per-message delivery callback (triggered by poll() or flush())
# when a message has been successfully delivered or permanently
# failed delivery (after retries).
from confluent_kafka.schema_registry import SchemaRegistryClient
from confluent_kafka.schema_registry.avro import AvroSerializer
from confluent_kafka.serialization import StringSerializer


def delivery_callback(err, msg):
    if err:
        sys.stderr.write("%% Message failed delivery: %s\n" % err)
    else:
        sys.stderr.write(
            "%% Message delivered to %s [%d] @ %d\n"
            % (msg.topic(), msg.partition(), msg.offset())
        )


if __name__ == "__main__":
    bootstrap_servers = "127.0.0.1:39092"
    schema_registry_servers = "http://127.0.0.1:48081"
    schema_registry_conf = {"url": schema_registry_servers}
    schema_registry_client = SchemaRegistryClient(schema_registry_conf)

    value_schema = fastavro.schema.load_schema("data/Employee.avsc")
    print(value_schema)
    avro_serializer = AvroSerializer(value_schema,
                                     schema_registry_client,
                                     )

    producer_conf = {'bootstrap.servers': bootstrap_servers,
                     'key.serializer': StringSerializer('utf_8'),
                     'value.serializer': avro_serializer}

    avro_producer = SerializingProducer(producer_conf)

    avro_producer.produce(
        topic="employees2",
        key=str(uuid.uuid4()),
        value=dict(
            id=1,
            name="Felix",
            role="Eng",
            company="Philips",
            eventDate=datetime.utcnow(),
            address=dict(street="Murrysville", zip=15668))
    )

    avro_producer.flush()

```

**Comment by scottbelden** [comment]
I'm not sure if this is the problem, but `load_schema` in the following line can return a list of schemas (a union in avro):

```
value_schema = fastavro.schema.load_schema("data/Employee.avsc")
```

Is it possible that the schema registry is expecting just a single schema (traditionally a single dictionary)?

**Comment by FelixKJose** [comment]
why is `value_schema = fastavro.schema.load_schema("data/Employee.avsc")`  returning list than a dictionary. @scottbelden Any idea how to get a schema of a nested object [dependent object stored as different .avsc files] as a single dictionary with fastavro?

**Comment by FelixKJose** [comment]
@mhowlett Any suggestions?

**Comment by scottbelden** [comment]
@FelixKJose You can take a look at this issue which talks about the problem. It was originally done the way it currently is because 1) it was easier and 2) it is still valid in terms of avro.

I haven't gotten around to trying to fix the problem yet, but one thing you could try is to take the last schema from that union. So you would change your example code to this:

value_schema = fastavro.schema.load_schema("data/Employee.avsc")[-1]

I'm not sure it that will work (and if it does, it might only work in some cases), but it might because in the list of schemas, the last one should be the overall schema.

**Comment by FelixKJose** [comment]
@scottbelden 
I am getting following error after making that change:

> {'type': 'record', 'name': 'Employee', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'name', 'type': 'string'}, {'name': 'role', 'type': 'string'}, {'name': 'company', 'type': 'string'}, {'name': 'eventDate', 'type': {'logicalType': 'timestamp-millis', 'type': 'long'}}, {'name': 'address', 'type': 'Address'}], '__fastavro_parsed': True, '__named_schemas': {'Address': {'type': 'record', 'name': 'Address', 'fields': [{'name': 'street', 'type': 'string'}, {'name': 'zip', 'type': 'int'}]}, 'Employee': {'type': 'record', 'name': 'Employee', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'name', 'type': 'string'}, {'name': 'role', 'type': 'string'}, {'name': 'company', 'type': 'string'}, {'name': 'eventDate', 'type': {'logicalType': 'timestamp-millis', 'type': 'long'}}, {'name': 'address', 'type': 'Address'}]}}}
> Traceback (most recent call last):
>   File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script

>   File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "/Users/xxxxx/PycharmProjects/ConfluentAvroKafkaProducer/employee_producer.py", line 35, in <module>
>     schema_registry_client,
>   File "/Users/xxxxx/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/schema_registry/avro.py", line 173, in __init__
>     schema = _schema_loads(schema_str)
>   File "/Users/xxxxx/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/schema_registry/avro.py", line 62, in _schema_loads
>     schema_str = schema_str.strip()
> AttributeError: 'dict' object has no attribute 'strip'
> python-BaseException

**Comment by scottbelden** [comment]
I'm not very familiar with this library (just fastavro), but I think `AvroSerializer` takes in the schema as a string, not a dictionary. So you could try doing a `json.dumps(value_schema)` to get the string form.

**Comment by FelixKJose** [comment]
@scottbelden I had tried that but unfortunately I am getting following error:

> Connected to pydev debugger (build 202.7660.27)
> {'type': 'record', 'name': 'Employee', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'name', 'type': 'string'}, {'name': 'role', 'type': 'string'}, {'name': 'company', 'type': 'string'}, {'name': 'address', 'type': 'Address'}], '__fastavro_parsed': True, '__named_schemas': {'Address': {'type': 'record', 'name': 'Address', 'fields': [{'name': 'street', 'type': 'string'}, {'name': 'zip', 'type': 'int'}]}, 'Employee': {'type': 'record', 'name': 'Employee', 'fields': [{'name': 'id', 'type': 'int'}, {'name': 'name', 'type': 'string'}, {'name': 'role', 'type': 'string'}, {'name': 'company', 'type': 'string'}, {'name': 'address', 'type': 'Address'}]}}}
> Traceback (most recent call last):
>   File "/Users/******/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/serializing_producer.py", line 172, in produce
>     value = self._value_serializer(value, ctx)
>   File "/Users/******/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/schema_registry/avro.py", line 217, in __call__
>     self._schema)
>   File "/Users/******/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 338, in register_schema
>     body=request)
>   File "/Users/******/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 127, in post
>     return self.send_request(url, method='POST', body=body)
>   File "/Users/******/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 176, in send_request
>     response.json().get('message'))
> confluent_kafka.schema_registry.error.SchemaRegistryError: Input schema is an invalid Avro schema (HTTP status code 422, SR code 42201)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/******/PycharmProjects/ConfluentAvroKafkaProducer/.venv/lib/python3.7/site-packages/confluent_kafka/serializing_producer.py", line 174, in produce
>     raise ValueSerializationError(se)
> confluent_kafka.error.ValueSerializationError: KafkaError{code=_VALUE_SERIALIZATION,val=-161,str="Input schema is an invalid Avro schema (HTTP status code 422, SR code 42201)"}
> python-BaseException


```
if __name__ == "__main__":
    bootstrap_servers = "127.0.0.1:39092"
    schema_registry_servers = "http://127.0.0.1:48081"
    schema_registry_conf = {"url": schema_registry_servers}
    schema_registry_client = SchemaRegistryClient(schema_registry_conf)

    value_schema = fastavro.schema.load_schema("data/Employee.avsc")[-1]
    print(value_schema)
    avro_serializer = AvroSerializer(json.dumps(value_schema),
                                     schema_registry_client,
                                     )

    producer_conf = {'bootstrap.servers': bootstrap_servers,
                     'key.serializer': StringSerializer('utf_8'),
                     'value.serializer': avro_serializer}

    avro_producer = SerializingProducer(producer_conf)

    avro_producer.produce(
        topic="employees2",
        key=str(uuid.uuid4()),
        value=dict(
            id=1,
            name="Felix",
            role="Eng",
            company="Philips",
            eventDate=datetime.utcnow(),
            address=dict(street="Murrysville", zip=15668))
    )

    avro_producer.flush()
```

**Comment by FelixKJose** [comment]
@mhowlett Could you please help me on this?

**Comment by mhowlett** [comment]
suggest looking at this example as a template of how to do this: https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/avro_producer.py

**Comment by scottbelden** [comment]
@FelixKJose I think I resolved the issue with `load_schema` so that it won't create union schemas. You could try updating to fastavro version `1.2.0` and see if that helps

**Comment by FelixKJose** [comment]
@scottbelden Yes it worked once I upgraded to fastavro 1.2.0. Thank you so much for your continued help. Seriously it was big relief for me from getting unblocked on this issue.

**Comment by scottbelden** [comment]
Great! I know you weren't the only one running into that issue with `load_schema` so I'm glad it worked.

**Comment by 300LiterPropofol** [comment]
Thanks @scottbelden for your awesome work! 
For anyone who is upcoming, I felt a bit confused reading through the above discussion and understanding what was actually fixed in fastavro 1.2.0. So I would like to write a bit more here after I tested in case anyone needs it.
The problem fastavro 1.2.0 fixed is: One already types code like below but still get error:
"""
value_schema = fastavro.schema.load_schema("data/Employee.avsc")[-1]
    avro_serializer = AvroSerializer(json.dumps(value_schema),
                                     schema_registry_client,
                                     )
"""
After updating fastavro >=1.2.0, the above syntax will work.
The problem fastavro 1.2.0 does not fix is: would like `<load_schema>` load the parent object when the .avsc file is a JSON array/avro union. So `<fastavro.schema.load_schema()>` still returns a list now and does not guarantee the nesting object dependency inside the union.

**Comment by scottbelden** [comment]
@300LiterPropofol Are you able to provide an example (either here or on the fastavro issues) of the problem you are seeing so that I can see if it's something that should be fixed?

**Comment by 300LiterPropofol** [comment]
It is the return value of `<fastavro.schema.load_schema()>` This value is still a list with all schema objects together, so there still needs to be a `<-1>` in the end to get the last object in this schema array. I saw https://github.com/fastavro/fastavro/issues/476 has been resolved and merged, but  `<value_schema = fastavro.schema.load_schema("data/Employee.avsc")>` still does not return a single parent schema object when data/Employee.avsc is a JSON array/avro union.

**Comment by scottbelden** [comment]
Given a union schema, there is not always a clear "parent" schema. For example, if I have a union schema defined like this:

```json
[
    {
        "name": "A",
        "type": "record",
        "fields": [
            {"name": "b", "type": "B"},
            {"name": "c", "type": "C"}
        ]
    },
    {
        "name": "D",
        "type": "record",
        "fields": [
            {"name": "e", "type": "E"},
            {"name": "f", "type": "F"}
        ]
    }
]
```

Then there isn't a clear parent because `A` and `D` are separate schemas that don't refer to each other.

**Comment by 300LiterPropofol** [comment]
Aha so this "return as a list" feature is deliberately kept? I thought it was changed after https://github.com/fastavro/fastavro/issues/476 resoved.

**Comment by scottbelden** [comment]
The issue there was if your overall schema was just a single JSON schema, the result of `load_schema` would be a list (avro union). So the bug fixed there was that if `Schema.avsc` is a single JSON schema, the result should be a single JSON schema. If `Schema.avsc` is a union schema, the result should be a union schema.

**Comment by 300LiterPropofol** [comment]
Ah okay! I get it now. Thank you. (^ ^)
